//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAMetadataEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPAMetadataEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Keywords.
        /// </summary>
        public static string LBL_EME_ISOK {
            get {
                return ResourceManager.GetString("LBL_EME_ISOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EME Topics &amp; Keywords.
        /// </summary>
        public static string LBL_EME_KEYWORDS_SIDEBAR {
            get {
                return ResourceManager.GetString("LBL_EME_KEYWORDS_SIDEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Keywords.
        /// </summary>
        public static string LBL_EME_PLACEK {
            get {
                return ResourceManager.GetString("LBL_EME_PLACEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EME Demo Page.
        /// </summary>
        public static string LBL_EME_SIDEBAR {
            get {
                return ResourceManager.GetString("LBL_EME_SIDEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPA Keywords.
        /// </summary>
        public static string LBL_EME_THEMEK {
            get {
                return ResourceManager.GetString("LBL_EME_THEMEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.S. Environmental Protection Agency Theme Keywords.
        /// </summary>
        public static string LBL_EME_THEMEK_TIP {
            get {
                return ResourceManager.GetString("LBL_EME_THEMEK_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Keywords.
        /// </summary>
        public static string LBL_EME_USERK {
            get {
                return ResourceManager.GetString("LBL_EME_USERK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Tool Tip.
        /// </summary>
        public static string LBL_EPA_TIP {
            get {
                return ResourceManager.GetString("LBL_EPA_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.S. Environmental Protection Agency.
        /// </summary>
        public static string LBL_EPA_TITLE {
            get {
                return ResourceManager.GetString("LBL_EPA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESRI Topics &amp; Keywords.
        /// </summary>
        public static string LBL_ESRI_KEYWORDS {
            get {
                return ResourceManager.GetString("LBL_ESRI_KEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Position:.
        /// </summary>
        public static string LBL_TEST_POSITION {
            get {
                return ResourceManager.GetString("LBL_TEST_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal workflow tracking position.
        /// </summary>
        public static string LBL_TEST_POSITION_TIP {
            get {
                return ResourceManager.GetString("LBL_TEST_POSITION_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EME Test Page.
        /// </summary>
        public static string LBL_TEST_SIDEBAR {
            get {
                return ResourceManager.GetString("LBL_TEST_SIDEBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Status:.
        /// </summary>
        public static string LBL_TEST_STATUS {
            get {
                return ResourceManager.GetString("LBL_TEST_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal workflow tracking status.
        /// </summary>
        public static string LBL_TEST_STATUS_TIP {
            get {
                return ResourceManager.GetString("LBL_TEST_STATUS_TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPA EditorPage Test.
        /// </summary>
        public static string LBL_TEST_TITLE {
            get {
                return ResourceManager.GetString("LBL_TEST_TITLE", resourceCulture);
            }
        }
    }
}
